### ISSUE TITLE
date filter

### ISSUE THREAD

**Issue by kenjclemente** [bevingtona/planetR#13]
Hi very cool product! just wanted help on how to specify list of exact dates as filter instead of the date range? (for example I have listed 15 dates where low tide conditions are expected). Many thanks!

**Comment by bevingtona** [comment]
Great idea, I added this functionality. You'll have to update the package. 

Using the Orders API example in the README, try: 

```
planet_order(api_key = api_key, 
             bbox = bbox, 
             list_dates = c("2021-01-01","2020-02-14"),
             cloud_lim = cloud_lim, 
             item_name = item_name, 
             product = product,
             order_name = exportfolder)

**Comment by bevingtona** [comment]
closed for inactivity, feel free to re-open if needed
