### ISSUE TITLE
Limit the download images to the latest image

### ISSUE THREAD

**Issue by agronomofiorentini** [bevingtona/planetR#14]
Dear contributor,
I have finally set the API key and now it is working perfectly. #12 

Congrants and thanks to develop this package.

I kidly ask you if it is possible to add an additional argument to planet_order that request to download only  the latest available image for those parameters.

Best regards

**Comment by bevingtona** [comment]
Great idea! Update the package and there is now a parameter in `planet_order` called `mostrecent`. It is and integer of how many of the most recent images will be downloaded. Default is 0 (download all images). But if you set to 1 it will download the most recent, or set to 10 it will download the 10 most recent. 
Let me know how it goes :)

**Comment by agronomofiorentini** [comment]
I will test it as soon as possible and I will give you back a feedback.

Thanks for the effort.

**Comment by agronomofiorentini** [comment]
It is working perfectly.

Thanks
