### ISSUE TITLE
subscript out of bounds

### ISSUE THREAD

**Issue by agronomofiorentini** [bevingtona/planetR#19]
Dear creator,
I am trying to download the images of the "PSScene4Band" by using the tool that you have developed but i am receving the following error output

> Error in permissions[, 1] : subscript out of bounds

I have setted correctly the api key because I had previously successfully downloaded the images.

I will report here all the information in order to reproduce the error

```
class      : Extent 
xmin       : 13.38829 
xmax       : 13.39752 
ymin       : 43.60996 
ymax       : 43.61316 

date_start<-2022-05-10
date_end<-2022-05-18

most_recent=2
cloud_lim = 0.2
item_name= PSScene4Band
product = analytic_sr
```

could you please help me to understand and fix the issue.

Thanks as always.

**Comment by para2x** [comment]
Same problem here

**Comment by agronomofiorentini** [comment]
Any news about this issue?

**Comment by agronomofiorentini** [comment]
Dear all i have solved the issue by changing the way that i was using the planetR package.

by using the same information as reported before, and running the following code, the downloding process worked perfectly.

```
planet_order(api_key = api_key, 
             bbox = bbox, 
             date_end = date_end,
             date_start = date_start,
             cloud_lim = cloud_lim, 
             item_name = "PSScene", 
             product_bundle = "analytic_8b_sr_udm2",
             asset = "ortho_analytic_8b_sr",
             mostrecent = 1,
             order_name = exportfolder)
```

Please @para2x, let me know if you are set well now.
