### ISSUE TITLE
Implementing Planet's Orders API

### ISSUE THREAD

**Issue by elistockwell** [bevingtona/planetR#7]
First of all, thanks for making this package!  There is very little support outside of Python for the Planet API, and I'm relatively new to APIs in general so having your code to look at was a real help.  I believe right now you are exclusively using Planet's Data API?  I'm not sure if you've looked at or worked with the Orders API, but it has some useful aspects like the built in clipping tool that clips images before download to save data (it seems like your download_withClip function clips them after but correct me if I'm wrong), and the orders themselves show up on the Planet account similar to orders placed using the Planet Explorer (they can be downloaded again using the order_id).  I've written a function that uses your planet_search function to get item_ids and then places an order with those ids and clips them to the AOI.  Let me know if this is something you would find useful and I can submit it with a pull request.

**Comment by bevingtona** [comment]
Awesome! I haven't looked in to integrating the Orders API. Any progress you've made with the new Orders API is most welcome as a PR. 
Thanks!

**Comment by bevingtona** [comment]
Thanks for this, the Orders API functions are great. I'll close this issue for now.
