### ISSUE TITLE
hexagon logo

### ISSUE THREAD

**Issue by PythonCoderUnicorn** [bevingtona/planetR#9]
Hello,

I made a hexagon logo and was wondering if you are interested in using this design. I can modify it if you like.

If you do like it, please credit me as Zane Dax `@StarTrek_Lt` 

![planetr](https://user-images.githubusercontent.com/55933131/143517480-c71ab652-5443-4b8d-b441-231d9998593a.png)
.

**Comment by bevingtona** [comment]
Thanks for your contribution. I don't think this logo conveys what the package does.
